### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Ataurr** [pixelartdev/Pixelart-Verifier#2]
Hi brother
i really need your help. 

As i am not using Aqua verifier before and try to use your Pixelart Verifier. 

But now when we see every user post showing "Unknowen Support Status" and i cant verify there purchase.

Is it possible to check when a user try to create a support ticket or support reply. this will ask a purchase code and this will check if this user support expired or not. 

Thanks very much for your help

**Comment by Ataurr** [comment]
Hi

I have found the details where we have all purchase code details under "_cw_purchase_code" meta_key

```
a:6:{
s:13:"purchase_code";s:36:"0b*****-7955-4595-b1bb-027031e9ac48";
s:9:"item_name";s:41:"AA product name template";
s:7:"item_id";s:8:"124338**";
s:10:"created_at";s:30:"Wed Mar 02 01:04:40 +1100 2016";
s:5:"buyer";s:8:"Buyer_UserName";
s:7:"licence";s:15:"Regular License";
} 
```

And i can easily print the value from db 

```
$p_info = get_user_meta( $user_id, '_cw_purchase_code', true);
$bb = $p_info['purchase_code'];
print_r($bb);
```

Now i am confused how we can include the purchase details with  your  plugin.

can you please help me :)

Till yesterday i  was using  this plugin https://wordpress.org/plugins/cloudwork-verifi/
So if easily we can include  with this so others user also will be benefit with this plugin

Thanks very much

**Comment by Ataurr** [comment]
Hell yeah i have added new function with your purchase code checker  ;)

**Comment by derDeno** [comment]
That's great!

**Comment by derDeno** [comment]
Sorry that we couldn't help you, because we didn't know how the other plugin saves the info.

**Comment by Ataurr** [comment]
We have also added a button in front page. when admin see "Unknowen Support Status"

Just click and verify this user info.

But i am not sure any others way all user can be verify :( without press "upgrade" one by one user

If you know How it can be that will be great :)

**Comment by derDeno** [comment]
We are actually resolving this issue in the next version and
implementing a way where you can build your custom extensions without
loosing them in every update we make. We are also implementing custom
hooks to do custom stuff like after the registration or changing the
user role based on the license or support type or item purchased. So
stay tuned it is in it final development this week. 

Regards

**Comment by Ataurr** [comment]
Great.

also add a notice system when support expired they will see a notice to purchase support again ;)
